<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page{
            size:A4 landscape;
            margin:20px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1b2a41;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1b2a41;
            font-size: 22px;
        }
        .header p {
            margin: 4px 0;
            color: #555;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            text-align: left;
            font-size: 11px;
    word-wrap: break-word; /* wraps long text */
        }
        th {
            background-color: #1b2a41;
            color: white;
            padding: 6px;
            border: 1px solid #ddd;
            word-break: break-word;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
            word-break: break-word;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        h3 {
            color: #1b2a41;
            margin-bottom: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $subTitle }}</p>
        <p>Generated on: {{ $generatedOn }}</p>
    </div>

    <table>
        <thead>
            <tr>
            <th>No.</th>
                <th>Customer Name</th>
                <th>Shop Name</th>
                <th>Contact</th>
                <th>City</th>
                <th>Total Credit Sale</th>
                <th>Last Balance</th>
                <th>Last Credit Sale</th>
            </tr>
        </thead>
        <tbody>
            @foreach($customers as $index => $customer)
               <tr>
                <td>{{$index+1}}</td>
                <td>{{$customer->name ?? 'Walk-in Customer'}}</td>
                <td>{{$customer->shop_name ?? 'N/A'}}</td>
                <td>{{$customer->contact ?? 'N/A'}}</td>
                <td>{{$customer->city ?? 'N/A'}}</td>
                    <td>{{ $customer->credit_sales_count ?? 0 }}</td>
                    <td>{{$customer->current_balance ?? '0'}}</td>
                    <td>
    @php
        $latestCreditSale = $customer->sales
            ->where('payment_type', 'credit')
            ->sortByDesc('created_at')
            ->first();
    @endphp

    @if($latestCreditSale)
        {{ $latestCreditSale->created_at->timezone('Asia/Karachi')->format('Y-m-d g:i:A') }}
    @else
        N/A
    @endif
</td>
               </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by POS System | © {{ date('Y') }}</p>
    </div>
    @if(isset($isPrint) && $isPrint)
<script>
    window.onload = function() {
        window.print();
    };
</script>
@endif
</body>
</html>
