<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page {
    size: A4 landscape;
    margin: 20px;
}

        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1b2a41;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1b2a41;
            font-size: 22px;
        }
        .header p {
            margin: 4px 0;
            color: #555;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            text-align: left;
            font-size: 11px;
            table-layout: fixed; /* forces equal column width */
    word-wrap: break-word; /* wraps long text */
        }
        th {
            background-color: #1b2a41;
            color: white;
            padding: 6px;
            border: 1px solid #ddd;
            word-break: break-word;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
            word-break: break-word;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        h3 {
            color: #1b2a41;
            margin-bottom: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $subTitle }}</p>
        <p>Generated on: {{ $generatedOn }}</p>
    </div>

    <table>
        <thead>
            <tr>
            <th>No.</th>
                <th>Product Name</th>
                <th>Category</th>
                <th>Purchased Price</th>
                <th>Sold Price</th>
                <th>Total Stock</th>
                <th>Unit</th>
                <th>Total Price</th>
                <th>Sold Quantity</th>
                <th>Remaining Quantity</th>
                <th>Purchase Date</th>
                <th>Supplier Name</th>
                <th>Company</th>
                <th>Address</th>
                <th>Contact Info</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purchases as $index => $purchase)
                @php
                    $totalStockValue = $purchase->purchased_price * $purchase->quantity;
                    $soldValue = $purchase->sold_quantity * $purchase->sold_price;
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $purchase->product_name }}</td>
                    <td>{{ $purchase->category->name ?? 'N/A' }}</td>
                    <td>Rs {{ number_format($purchase->purchased_price, 2) }}</td>
                    <td>Rs {{ number_format($purchase->sold_price, 2) }}</td>
                    <td>{{ $purchase->quantity }}</td>
                    <td>{{ $purchase->unit }}</td>
                    <td>Rs {{ number_format($totalStockValue, 2) }}</td>
                    <td>{{ $purchase->sold_quantity }} (Rs {{ number_format($soldValue, 2) }})</td>
                    <td>{{ $purchase->quantity - $purchase->sold_quantity }}</td>
                    <td>{{ \Carbon\Carbon::parse($purchase->purchase_date)->format('d-M-Y h:i A') }}</td>
                    <td>{{ $purchase->supplier->name ?? 'N/A' }}</td>
                    <td>{{ $purchase->supplier->company ?? 'N/A' }}</td>
                    <td>{{ $purchase->supplier->address ?? 'N/A' }}</td>
                    <td>{{ $purchase->supplier->contact_info ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by POS System | © {{ date('Y') }}</p>
    </div>
    @if(isset($isPrint) && $isPrint)
<script>
    window.onload = function() {
        window.print();
    };
</script>
@endif
</body>
</html>
