<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1b2a41;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1b2a41;
            font-size: 22px;
        }
        .header p {
            margin: 4px 0;
            color: #555;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            text-align: left;
            font-size: 11px;
            table-layout: fixed; /* forces equal column width */
    word-wrap: break-word; /* wraps long text */
        }
        th {
            background-color: #1b2a41;
            color: white;
            padding: 6px;
            border: 1px solid #ddd;
            word-break: break-word;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
            word-break: break-word;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        h3 {
            color: #1b2a41;
            margin-bottom: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $subTitle }}</p>
        <p>Generated on: {{ $generatedOn }}</p>
    </div>

    <table>
        <thead>
            <tr>
            <th>No.</th>
                <th>Supplier Name</th>
                <th>Company</th>
                <th>Address</th>
                <th>Contact Info</th>
                <th>Total Purchases</th>
                <th>Total Purchases (Rs)</th>

            </tr>
        </thead>
        <tbody>
            @foreach($suppliers as $index => $supplier)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $supplier->name ?? 'N/A' }}</td>
                    <td>{{ $supplier->company ?? 'N/A' }}</td>
                    <td>{{ $supplier->address ?? 'N/A' }}</td>
                    <td>{{ $supplier->contact_info ?? 'N/A' }}</td>
                    <td>{{$supplier->purchases_count ?? '0'}}</td>
                    <td>Rs {{$supplier->total_purchase_amount ?? '0'}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by POS System | © {{ date('Y') }}</p>
    </div>
    @if(isset($isPrint) && $isPrint)
<script>
    window.onload = function() {
        window.print();
    };
</script>
@endif
</body>
</html>
