<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page{
            margin:15px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1b2a41;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .supplier-detail p{
            font-size:12px;
        }
        .header h1 {
            margin: 0;
            color: #1b2a41;
            font-size: 22px;
        }
        .header p {
            margin: 4px 0;
            color: #555;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            text-align: left;
            font-size: 11px;
    word-wrap: break-word; /* wraps long text */
        }
        th {
            background-color: #1b2a41;
            color: white;
            padding: 6px;
            border: 1px solid #ddd;
            word-break: break-word;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
            word-break: break-word;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        h3 {
            color: #1b2a41;
            margin-bottom: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $subTitle }}</p>
        <p>Generated on: {{ $generatedOn }}</p>
    </div>

    <div class="supplier-detail">
        <p>Category: <strong>{{$category->name ?? 'N/A'}}</strong></p>
        <p>description: <strong>{{$category->description ?? 'N/A'}}</strong></p>
    </div>
    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Product Name</th>
                <th>Purchased Price</th>
                <th>Total Stock</th>
                <th>Unit</th>
                <th>Total Price</th>
                <th>Available Stock</th>
                <th>Available Stock (Rs)</th>
                <th>Purchase Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purchases as $index => $purchase)
                @php
                    $totalStockValue = $purchase->purchased_price * $purchase->quantity;
                @endphp
                <tr>
                    <td>{{ $index + 1}}</td>
                    <td>{{ $purchase->product_name }}</td>
                    <td>Rs {{ number_format($purchase->purchased_price, 2) }}</td>
                    <td>{{ $purchase->quantity }}</td>
                    <td>{{ $purchase->unit }}</td>
                    <td>Rs {{ number_format($totalStockValue, 2) }}</td>
                    <td>{{$purchase->quantity-$purchase->sold_quantity}}</td>
        <td>Rs {{number_format(($purchase->quantity-$purchase->sold_quantity)*$purchase->purchased_price,2)}}</td>
                    <td>{{ \Carbon\Carbon::parse($purchase->purchase_date)->format('d-M-Y h:i A') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by POS System | © {{ date('Y') }}</p>
    </div>
    @if(isset($isPrint) && $isPrint)
<script>
    window.onload = function() {
        window.print();
    };
</script>
@endif
</body>
</html>